pantalla:
  - ancho: 4
  - alto: 4
configuracion:
  - vel_personaje: 3
    margen_scroll: 45
tipos:
  - nombre: arbol
    imagen:  path/a/imagen.png
  - nombre: castillo
    imagen:  path/a/imagen.png
    ancho_base: 2
    alto_base: 2
    pixel_ref_x: 30
    pixel_ref_y: 30
  - nombre: juana_de_arco
    imagen: C:/juana.png
    pfs: 15
    delay: 15
escenario:
  - nombre: orleans
    size_x: 100
    size_y: 100
    entidades:
      - {x: 10, y: 15, tipo: tierra}
      - {x: 11, y: 12, tipo: agua}
      - {x: 12, y: 13, tipo: castillo}
    protagonista:
      - tipo: juana_de_arco
        x: 50
        y: 60