pantalla:
    ancho: 1024
    alto: 600
    margen_scroll: 45
    velocidad_scroll: 45
configuracion:
    dt: 20
tipos_entidades:
  - nombre: troncoNESW
    imagen: resources/troncoNESW31.png
    ancho_base: 1
    alto_base: 3
    pixel_ref_x: 96
    pixel_ref_y: 22
    fps: 0
    delay: 0
    ancho_sprite: 128
    alto_sprite: 83
    cantidad_sprites: 1
  - nombre: troncoNWSE
    imagen: resources/troncoNWSE13.png
    ancho_base: 3
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 22
    fps: 0
    delay: 0
    ancho_sprite: 128
    alto_sprite: 83
    cantidad_sprites: 1
  - nombre: chancho
    imagen: resources/chanchos.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 17
    pixel_ref_y: 24
    fps: 20
    delay: 1
    ancho_sprite: 48
    alto_sprite: 44
    cantidad_sprites: 15
  - nombre: cartel
    imagen: resources/cartel.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 16
    pixel_ref_y: 16
    fps: 0
    delay: 0
    ancho_sprite: 32
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: chanchoDelay
    imagen: resources/chanchos.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 17
    pixel_ref_y: 24
    fps: 20
    delay: 2
    ancho_sprite: 48
    alto_sprite: 44
    cantidad_sprites: 15
  - nombre: mago
    imagen: resources/mago.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 30
    pixel_ref_y: 32
    fps: 10
    delay: 0
    ancho_sprite: 60
    alto_sprite: 60
    cantidad_sprites: 5
    sight_radius: 3
    speed: 3
  - nombre: cubo
    imagen: resources/cubo_1_2.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 16
    pixel_ref_y: 16
    fps: 0
    delay: 0
    ancho_sprite: 32
    alto_sprite: 32
    cantidad_sprites: 1
    sight_radius: 3
    speed: 3
  - nombre: arbol
    imagen: resources/arbol.png
    ancho_base: 1.9
    alto_base: 1.9
    pixel_ref_x: 49
    pixel_ref_y: 84
    fps: 0
    delay: 0
    ancho_sprite: 88
    alto_sprite: 143
    cantidad_sprites: 1
tipos_terrenos:
  - nombre: agua
    imagen: resources/agua.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
    solid: true
  - nombre: pasto
    imagen: resources/pasto.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: piedra
    imagen: resources/piedra.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
tipos_recursos:
  - nombre: carne
    imagen: resources/carne.png
    ancho_base: 1
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 2
    ancho_sprite: 64
    alto_sprite: 32
    capacidad: 100
  - nombre: oro
    imagen: resources/oro.png
    ancho_base: 1
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 3
    ancho_sprite: 64
    alto_sprite: 35
    capacidad: 100
escenario:
    nombre: Orleans
    size_x: 25
    size_y: 25
    max_resources: 25000
    terrenos:
      - {x: 0, y: 0, tipo: agua }
      - {x: 0, y: 1, tipo: agua }
      - {x: 0, y: 2, tipo: agua }
      - {x: 0, y: 3, tipo: agua }
      - {x: 0, y: 4, tipo: piedra }
      - {x: 0, y: 5, tipo: piedra }
      - {x: 0, y: 6, tipo: piedra }
      - {x: 0, y: 7, tipo: piedra }
      - {x: 1, y: 0, tipo: agua }
      - {x: 1, y: 1, tipo: agua }
      - {x: 1, y: 2, tipo: agua }
      - {x: 1, y: 3, tipo: agua }
      - {x: 1, y: 4, tipo: piedra }
      - {x: 1, y: 5, tipo: piedra }
      - {x: 1, y: 6, tipo: piedra }
      - {x: 1, y: 7, tipo: piedra }
      - {x: 2, y: 0, tipo: agua }
      - {x: 2, y: 1, tipo: agua }
      - {x: 2, y: 2, tipo: agua }
      - {x: 2, y: 3, tipo: agua }
      - {x: 2, y: 4, tipo: piedra }
      - {x: 2, y: 5, tipo: piedra }
      - {x: 2, y: 6, tipo: piedra }
      - {x: 2, y: 7, tipo: piedra }
      - {x: 3, y: 0, tipo: piedra }
      - {x: 3, y: 1, tipo: piedra }
      - {x: 3, y: 2, tipo: piedra }
      - {x: 3, y: 3, tipo: piedra }
      - {x: 3, y: 4, tipo: piedra }
      - {x: 3, y: 5, tipo: piedra }
      - {x: 3, y: 6, tipo: piedra }
      - {x: 3, y: 7, tipo: piedra }
      - {x: 4, y: 4, tipo: piedra }
      - {x: 4, y: 5, tipo: piedra }
      - {x: 4, y: 6, tipo: piedra }
      - {x: 4, y: 7, tipo: piedra }
      - {x: 5, y: 4, tipo: piedra }
      - {x: 5, y: 5, tipo: piedra }
      - {x: 5, y: 6, tipo: piedra }
      - {x: 5, y: 7, tipo: piedra }
      - {x: 6, y: 4, tipo: piedra }
      - {x: 6, y: 5, tipo: piedra }
      - {x: 6, y: 6, tipo: piedra }
      - {x: 6, y: 7, tipo: piedra }
      - {x: 7, y: 4, tipo: piedra }
      - {x: 7, y: 5, tipo: piedra }
      - {x: 7, y: 6, tipo: piedra }
      - {x: 7, y: 7, tipo: piedra }
      - {x: 8, y: 4, tipo: piedra }
      - {x: 8, y: 5, tipo: piedra }
      - {x: 8, y: 6, tipo: piedra }
      - {x: 8, y: 7, tipo: piedra }
      - {x: 9, y: 4, tipo: piedra }
      - {x: 9, y: 5, tipo: piedra }
      - {x: 9, y: 6, tipo: piedra }
      - {x: 9, y: 7, tipo: piedra }
    entidades:
      - {x: 2, y: 9, tipo: cartel }
      - {x: 5, y: 3, tipo: cartel }
      - {x: 5, y: 9, tipo: cartel }
      - {x: 3, y: 11, tipo: troncoNESW }
      - {x: 3, y: 15, tipo: troncoNESW }
      - {x: 3, y: 14, tipo: chancho }
      - {x: 0, y: 14, tipo: troncoNWSE }
      - {x: 4, y: 14, tipo: troncoNWSE }
      - {x: 10, y: 10, tipo: chanchoDelay }
      - {x: 10, y: 11, tipo: chanchoDelay }
      - {x: 11, y: 10, tipo: chancho }
      - {x: 11, y: 11, tipo: chancho }
      - {x: 5, y: 5, tipo: chancho }
      - {x: 15, y: 15, tipo: arbol }
      - {x: 15, y: 17, tipo: arbol }
      - {x: 17, y: 15, tipo: arbol }
      - {x: 17, y: 17, tipo: arbol }
      - {x: 15, y: 4, tipo: arbol }
      - {x: 17, y: 4, tipo: arbol }
      - {x: 19, y: 4, tipo: arbol }
      - {x: 21, y: 4, tipo: arbol }
      - {x: 15, y: 6, tipo: arbol }
      - {x: 17, y: 6, tipo: arbol }
      - {x: 19, y: 6, tipo: arbol }
      - {x: 21, y: 6, tipo: arbol }
      - {x: 15, y: 8, tipo: arbol }
      - {x: 17, y: 8, tipo: arbol }
      - {x: 19, y: 8, tipo: arbol }
      - {x: 21, y: 8, tipo: arbol }
      - {x: 15, y: 10, tipo: arbol }
      - {x: 17, y: 10, tipo: arbol }
      - {x: 19, y: 10, tipo: arbol }
      - {x: 21, y: 10, tipo: arbol }
      - {x: 15, y: 11, tipo: arbol }
      - {x: 17, y: 11, tipo: arbol }
      - {x: 19, y: 11, tipo: arbol }
      - {x: 21, y: 11, tipo: arbol }
    jugadores:
      - name: Kybon
        isHuman: true
        entidades:
          - {x: 20, y: 20, tipo: cubo }
      - name: Franceses
        isHuman: true
        entidades:
          - {x: 3, y: 3, tipo: mago }
