pantalla:
    ancho: 640
    alto: 480
configuracion:
    vel_personaje: 3
    margen_scroll: 45
    velocidad_scroll: 45
    dt: 50
tipos_entidades:
  - nombre: troncoNESW
    imagen: resources/troncoNESW31.png
    ancho_base: 1
    alto_base: 3
    pixel_ref_x: 96
    pixel_ref_y: 22
    fps: 0
    delay: 0
    ancho_sprite: 128
    alto_sprite: 83
    cantidad_sprites: 1
  - nombre: troncoNWSE
    imagen: resources/troncoNWSE13.png
    ancho_base: 3
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 22
    fps: 0
    delay: 0
    ancho_sprite: 128
    alto_sprite: 83
    cantidad_sprites: 1
  - nombre: chancho
    imagen: resources/chanchos.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 17
    pixel_ref_y: 24
    fps: 20
    delay: 1
    ancho_sprite: 48
    alto_sprite: 44
    cantidad_sprites: 15
  - nombre: mago
    imagen: resources/mago.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 30
    pixel_ref_y: 30
    fps: 10
    delay: 0
    ancho_sprite: 60
    alto_sprite: 60
    cantidad_sprites: 5
tipos_terrenos:
  - nombre: agua
    imagen: resources/agua.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: pasto
    imagen: resources/pasto.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: piedra
    imagen: resources/piedra.png
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
escenario:
    nombre: orleans
    size_x: 100
    size_y: 100
    entidades:
      - {x: 10, y: 10, tipo: chancho }
      - {x: 10, y: 11, tipo: chancho }
      - {x: 11, y: 10, tipo: chancho }
      - {x: 11, y: 11, tipo: chancho }
      #- {x: 0, y: 6, tipo: chancho }
      #- {x: 0, y: 8, tipo: chancho }
      #- {x: 2, y: 4, tipo: chancho }
      #- {x: 2, y: 6, tipo: chancho }
      #- {x: 2, y: 8, tipo: chancho }
      #- {x: 2, y: 10, tipo: chancho }
      #- {x: 4, y: 4, tipo: chancho }
      #- {x: 4, y: 6, tipo: chancho }
      #- {x: 4, y: 8, tipo: chancho }
      #- {x: 4, y: 10, tipo: chancho }
      #- {x: 6, y: 6, tipo: chancho }
      #- {x: 6, y: 8, tipo: chancho }
      - {x: 3, y: 4, tipo: troncoNESW }
      - {x: 3, y: 8, tipo: troncoNESW }
      - {x: 3, y: 7, tipo: chancho }
      - {x: 0, y: 7, tipo: troncoNWSE }
      - {x: 4, y: 7, tipo: troncoNWSE }
    terrenos:
      - {x: 0, y: 0, tipo: agua }
      - {x: 1, y: 0, tipo: agua }
      - {x: 2, y: 0, tipo: agua }
      - {x: 0, y: 1, tipo: agua }
      - {x: 1, y: 1, tipo: agua }
      - {x: 0, y: 2, tipo: agua }
      - {x: 0, y: 3, tipo: piedra }
      - {x: 2, y: 1, tipo: piedra }
      - {x: 1, y: 2, tipo: piedra }
      - {x: 3, y: 0, tipo: piedra }
    protagonista:
      - {x: 3, y: 3, tipo: mago }
