pantalla:
    ancho: 640
    alto: 480
configuracion:
    vel_personaje: 3
    margen_scroll: 45
    velocidad_scroll: 45
tipos:
  - nombre: agua
    imagen: resources/agua.png
    ancho_base: 1
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: pasto
    imagen: resources/pasto.png
    ancho_base: 1
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: piedra
    imagen: resources/piedra.png
    ancho_base: 1
    alto_base: 1
    pixel_ref_x: 32
    pixel_ref_y: 0
    fps: 0
    delay: 0
    ancho_sprite: 64
    alto_sprite: 32
    cantidad_sprites: 1
  - nombre: chancho
    imagen: resources/chanchos.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 17
    pixel_ref_y: 24
    fps: 0
    delay: 1
    ancho_sprite: 48
    alto_sprite: 44
    cantidad_sprites: 15
  - nombre: mago
    imagen: resources/mago.png
    ancho_base: 0.5
    alto_base: 0.5
    pixel_ref_x: 30
    pixel_ref_y: 30
    fps: 0
    delay: 0
    ancho_sprite: 60
    alto_sprite: 60
    cantidad_sprites: 5
escenario:
    nombre: orleans
    size_x: 100
    size_y: 100
    entidades:
      - {x: 5, y: 5, tipo: chancho}
      - {x: 10, y: 10, tipo: chancho}
    terrenos:
      - {x: 1, y: 1, tipo: piedra}
      - {x: 0, y: 0, tipo: agua}
    protagonista:
      - tipo: mago
        x: 3
        y: 3
